version: "3"

services:
  image-server:
    build: ./docker/godev
    volumes:
      - ./server:/workspace
      - image-server-tmp:/workspace/tmp
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: ap-northeast-1
      IMAGE_SERVER_CONVERT_PARAMS: '[{"type":"mini","w":50,"h":50,"lossless":true}]'
      IMAGE_SERVER_BUCKET: bucket
      IMAGE_SERVER_S3URL: http://minio:9000

  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: sh
    command: -c 'mkdir -p /export/bucket && /usr/bin/minio server /export'

volumes:
  image-server-tmp:
  minio-data:
